sudo: false
language: android

# https://github.com/travis-ci/travis-ci/issues/3695
env:
  global:
      MALLOC_ARENA_MAX=2

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository

addons:
  apt_packages:
    - pandoc

script: ./gradlew build


after_failure:
after_failure:
  - pandoc app/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'
  - pandoc intenthelper/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'


after_script:
- for f in "app/build/outputs/lint-results*.html"; do pandoc $f -t plain; done
- for f in "intenthelper/build/outputs/lint-results*.html"; do pandoc $f -t plain; done